### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by hanc2006** [Artur-/form-lit2#1]
Hi,
I tried to run

`npm install`

to start working with the project. But I immediately got an error. The following dependencies obviously cannot be installed:

```
...
 "@vaadin/flow-frontend": "./target/flow-frontend",
 "@vaadin/form": "./target/flow-frontend/form",
...
```

**Comment by Artur-** [comment]
How on earth did you end up running this project? I don’t even know what it is 😀

It can be started using `mvn`which takes care of the missing files

You might want to look at a Fusion project from start.vaadin.com instead
